{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "2c9d5c51-8554-400a-9fbb-ff6b47389cab",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "========================================================================\n",
      "RCA REASONING SCAFFOLDER\n",
      "========================================================================\n",
      "Issue: Deviation in GMP environmental monitoring record review\n",
      "Final closure: Not yet closed\n",
      "------------------------------------------------------------------------\n",
      "H1 | Sampling procedure was not followed correctly | status=active\n",
      "   - Factor   [F1] Analyst may have misunderstood the sequence of sampling steps\n",
      "   - Factor   [F2] Procedure required repeated cross-checking across sections\n",
      "   - Evidence [E1] Step order confusion was mentioned during retrospective questioning\n",
      "   - Note     Possible procedural ambiguity rather than simple operator negligence\n",
      "\n",
      "H2 | Environmental fluctuation affected the result | status=narrowed\n",
      "   - Factor   [F1] Temporary room condition shift may have influenced results\n",
      "   - Factor   [F2] Monitoring context was not stable across the whole observation period\n",
      "   - Evidence [E1] Environmental log showed minor fluctuation near deviation time\n",
      "   - Note     Needs comparison with adjacent monitoring intervals\n",
      "\n",
      "H3 | Documentation entry compressed multiple contributing factors | status=active\n",
      "   - Factor   [F1] Final RCA format pushed reasoning toward a single neat explanation\n",
      "   - Factor   [F2] Alternative causal paths became less visible during write-up\n",
      "   - Evidence [E1] Draft notes contained broader possibilities than final narrative\n",
      "   - Note     Supports the idea of narrative compression under documentation pressure\n",
      "\n",
      "------------------------------------------------------------------------\n",
      "Total hypotheses: 3\n",
      "Active hypotheses: 3\n",
      "Premature closure warning: False\n",
      "Message: Reasoning remains open enough.\n",
      "========================================================================\n",
      "\n",
      "SUMMARY TABLE\n",
      "Hypothesis ID                                                   Hypothesis   Status Factor ID                                                                Factor Evidence ID                                                            Evidence  Notes Count\n",
      "           H1                Sampling procedure was not followed correctly   active        F1         Analyst may have misunderstood the sequence of sampling steps          E1 Step order confusion was mentioned during retrospective questioning            1\n",
      "           H1                Sampling procedure was not followed correctly   active        F2            Procedure required repeated cross-checking across sections                                                                                            1\n",
      "           H2                Environmental fluctuation affected the result narrowed        F1            Temporary room condition shift may have influenced results          E1      Environmental log showed minor fluctuation near deviation time            1\n",
      "           H2                Environmental fluctuation affected the result narrowed        F2 Monitoring context was not stable across the whole observation period                                                                                            1\n",
      "           H3 Documentation entry compressed multiple contributing factors   active        F1    Final RCA format pushed reasoning toward a single neat explanation          E1    Draft notes contained broader possibilities than final narrative            1\n",
      "           H3 Documentation entry compressed multiple contributing factors   active        F2          Alternative causal paths became less visible during write-up                                                                                            1\n",
      "\n",
      "Saved summary table to: rca_summary_table.csv\n",
      "Saved graph to: rca_reasoning_graph.png\n",
      "\n",
      "PREMATURE CLOSURE CHECK\n",
      "{'total_hypotheses': 3, 'active_hypotheses': 3, 'warning': False, 'message': 'Reasoning remains open enough.'}\n",
      "\n",
      "SIMULATING NARROWING...\n",
      "{'total_hypotheses': 3, 'active_hypotheses': 1, 'warning': True, 'message': 'Warning: reasoning may be prematurely narrowed. Only one active hypothesis remains before formal closure.'}\n",
      "\n",
      "Final closure set to: H1\n"
     ]
    }
   ],
   "source": [
    "from __future__ import annotations\n",
    "\n",
    "from dataclasses import dataclass, field\n",
    "from typing import List, Optional, Dict\n",
    "import pandas as pd\n",
    "import networkx as nx\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "\n",
    "# =========================\n",
    "# Data structures\n",
    "# =========================\n",
    "\n",
    "@dataclass\n",
    "class Factor:\n",
    "    id: str\n",
    "    description: str\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class Evidence:\n",
    "    id: str\n",
    "    description: str\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class Hypothesis:\n",
    "    id: str\n",
    "    description: str\n",
    "    status: str = \"active\"   # active / narrowed / closed / rejected\n",
    "    factors: List[Factor] = field(default_factory=list)\n",
    "    evidence: List[Evidence] = field(default_factory=list)\n",
    "    notes: List[str] = field(default_factory=list)\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class RCARecord:\n",
    "    issue: str\n",
    "    hypotheses: List[Hypothesis] = field(default_factory=list)\n",
    "    final_closure: Optional[str] = None\n",
    "\n",
    "\n",
    "# =========================\n",
    "# RCA scaffold logic\n",
    "# =========================\n",
    "\n",
    "class RCAReasoningScaffolder:\n",
    "    def __init__(self, issue: str):\n",
    "        self.rca = RCARecord(issue=issue)\n",
    "\n",
    "    def _next_hypothesis_id(self) -> str:\n",
    "        return f\"H{len(self.rca.hypotheses) + 1}\"\n",
    "\n",
    "    def _next_factor_id(self, hypothesis: Hypothesis) -> str:\n",
    "        return f\"F{len(hypothesis.factors) + 1}\"\n",
    "\n",
    "    def _next_evidence_id(self, hypothesis: Hypothesis) -> str:\n",
    "        return f\"E{len(hypothesis.evidence) + 1}\"\n",
    "\n",
    "    def _find_hypothesis(self, hypothesis_id: str) -> Hypothesis:\n",
    "        for h in self.rca.hypotheses:\n",
    "            if h.id == hypothesis_id:\n",
    "                return h\n",
    "        raise ValueError(f\"Hypothesis '{hypothesis_id}' not found.\")\n",
    "\n",
    "    def add_hypothesis(self, description: str, status: str = \"active\") -> str:\n",
    "        new_id = self._next_hypothesis_id()\n",
    "        self.rca.hypotheses.append(\n",
    "            Hypothesis(\n",
    "                id=new_id,\n",
    "                description=description,\n",
    "                status=status\n",
    "            )\n",
    "        )\n",
    "        return new_id\n",
    "\n",
    "    def add_factor(self, hypothesis_id: str, description: str) -> str:\n",
    "        h = self._find_hypothesis(hypothesis_id)\n",
    "        new_id = self._next_factor_id(h)\n",
    "        h.factors.append(Factor(id=new_id, description=description))\n",
    "        return new_id\n",
    "\n",
    "    def add_evidence(self, hypothesis_id: str, description: str) -> str:\n",
    "        h = self._find_hypothesis(hypothesis_id)\n",
    "        new_id = self._next_evidence_id(h)\n",
    "        h.evidence.append(Evidence(id=new_id, description=description))\n",
    "        return new_id\n",
    "\n",
    "    def add_note(self, hypothesis_id: str, note: str) -> None:\n",
    "        h = self._find_hypothesis(hypothesis_id)\n",
    "        h.notes.append(note)\n",
    "\n",
    "    def update_status(self, hypothesis_id: str, new_status: str) -> None:\n",
    "        allowed = {\"active\", \"narrowed\", \"closed\", \"rejected\"}\n",
    "        if new_status not in allowed:\n",
    "            raise ValueError(f\"Invalid status '{new_status}'. Allowed: {allowed}\")\n",
    "        h = self._find_hypothesis(hypothesis_id)\n",
    "        h.status = new_status\n",
    "\n",
    "    def set_final_closure(self, hypothesis_id: str) -> None:\n",
    "        h = self._find_hypothesis(hypothesis_id)\n",
    "        self.rca.final_closure = h.id\n",
    "        h.status = \"closed\"\n",
    "\n",
    "    def get_active_hypotheses(self) -> List[Hypothesis]:\n",
    "        return [h for h in self.rca.hypotheses if h.status in {\"active\", \"narrowed\"}]\n",
    "\n",
    "    def check_premature_closure(self) -> Dict[str, object]:\n",
    "        active = self.get_active_hypotheses()\n",
    "\n",
    "        warning = False\n",
    "        message = \"Reasoning remains open enough.\"\n",
    "\n",
    "        if len(active) <= 1 and self.rca.final_closure is None:\n",
    "            warning = True\n",
    "            message = (\n",
    "                \"Warning: reasoning may be prematurely narrowed. \"\n",
    "                \"Only one active hypothesis remains before formal closure.\"\n",
    "            )\n",
    "\n",
    "        if len(self.rca.hypotheses) == 1:\n",
    "            warning = True\n",
    "            message = (\n",
    "                \"Warning: only one hypothesis was considered. \"\n",
    "                \"Alternative explanations may not have been preserved.\"\n",
    "            )\n",
    "\n",
    "        return {\n",
    "            \"total_hypotheses\": len(self.rca.hypotheses),\n",
    "            \"active_hypotheses\": len(active),\n",
    "            \"warning\": warning,\n",
    "            \"message\": message\n",
    "        }\n",
    "\n",
    "    def summary_table(self) -> pd.DataFrame:\n",
    "        rows = []\n",
    "\n",
    "        for h in self.rca.hypotheses:\n",
    "            if not h.factors and not h.evidence:\n",
    "                rows.append({\n",
    "                    \"Hypothesis ID\": h.id,\n",
    "                    \"Hypothesis\": h.description,\n",
    "                    \"Status\": h.status,\n",
    "                    \"Factor ID\": \"\",\n",
    "                    \"Factor\": \"\",\n",
    "                    \"Evidence ID\": \"\",\n",
    "                    \"Evidence\": \"\",\n",
    "                    \"Notes Count\": len(h.notes)\n",
    "                })\n",
    "                continue\n",
    "\n",
    "            max_len = max(len(h.factors), len(h.evidence), 1)\n",
    "\n",
    "            for i in range(max_len):\n",
    "                factor = h.factors[i] if i < len(h.factors) else None\n",
    "                evidence = h.evidence[i] if i < len(h.evidence) else None\n",
    "\n",
    "                rows.append({\n",
    "                    \"Hypothesis ID\": h.id,\n",
    "                    \"Hypothesis\": h.description,\n",
    "                    \"Status\": h.status,\n",
    "                    \"Factor ID\": factor.id if factor else \"\",\n",
    "                    \"Factor\": factor.description if factor else \"\",\n",
    "                    \"Evidence ID\": evidence.id if evidence else \"\",\n",
    "                    \"Evidence\": evidence.description if evidence else \"\",\n",
    "                    \"Notes Count\": len(h.notes)\n",
    "                })\n",
    "\n",
    "        return pd.DataFrame(rows)\n",
    "\n",
    "    def print_summary(self) -> None:\n",
    "        print(\"\\n\" + \"=\" * 72)\n",
    "        print(\"RCA REASONING SCAFFOLDER\")\n",
    "        print(\"=\" * 72)\n",
    "        print(f\"Issue: {self.rca.issue}\")\n",
    "        print(f\"Final closure: {self.rca.final_closure if self.rca.final_closure else 'Not yet closed'}\")\n",
    "        print(\"-\" * 72)\n",
    "\n",
    "        for h in self.rca.hypotheses:\n",
    "            print(f\"{h.id} | {h.description} | status={h.status}\")\n",
    "\n",
    "            if h.factors:\n",
    "                for f in h.factors:\n",
    "                    print(f\"   - Factor   [{f.id}] {f.description}\")\n",
    "            else:\n",
    "                print(\"   - Factor   [none]\")\n",
    "\n",
    "            if h.evidence:\n",
    "                for e in h.evidence:\n",
    "                    print(f\"   - Evidence [{e.id}] {e.description}\")\n",
    "            else:\n",
    "                print(\"   - Evidence [none]\")\n",
    "\n",
    "            if h.notes:\n",
    "                for n in h.notes:\n",
    "                    print(f\"   - Note     {n}\")\n",
    "\n",
    "            print()\n",
    "\n",
    "        check = self.check_premature_closure()\n",
    "        print(\"-\" * 72)\n",
    "        print(f\"Total hypotheses: {check['total_hypotheses']}\")\n",
    "        print(f\"Active hypotheses: {check['active_hypotheses']}\")\n",
    "        print(f\"Premature closure warning: {check['warning']}\")\n",
    "        print(f\"Message: {check['message']}\")\n",
    "        print(\"=\" * 72 + \"\\n\")\n",
    "\n",
    "    def build_graph(self) -> nx.DiGraph:\n",
    "        G = nx.DiGraph()\n",
    "\n",
    "        issue_node = f\"Issue: {self.rca.issue}\"\n",
    "        G.add_node(issue_node, node_type=\"issue\")\n",
    "\n",
    "        for h in self.rca.hypotheses:\n",
    "            h_node = f\"{h.id}: {h.description}\"\n",
    "            G.add_node(h_node, node_type=\"hypothesis\", status=h.status)\n",
    "            G.add_edge(issue_node, h_node, edge_type=\"hypothesis\")\n",
    "\n",
    "            for f in h.factors:\n",
    "                f_node = f\"{f.id}: {f.description}\"\n",
    "                G.add_node(f_node, node_type=\"factor\")\n",
    "                G.add_edge(h_node, f_node, edge_type=\"factor\")\n",
    "\n",
    "            for e in h.evidence:\n",
    "                e_node = f\"{e.id}: {e.description}\"\n",
    "                G.add_node(e_node, node_type=\"evidence\")\n",
    "                G.add_edge(h_node, e_node, edge_type=\"evidence\")\n",
    "\n",
    "        return G\n",
    "\n",
    "    def plot_graph(self, save_path: str = \"rca_reasoning_graph.png\") -> None:\n",
    "        G = self.build_graph()\n",
    "        pos = nx.spring_layout(G, seed=42, k=1.0)\n",
    "\n",
    "        node_colors = []\n",
    "        for _, data in G.nodes(data=True):\n",
    "            node_type = data.get(\"node_type\")\n",
    "\n",
    "            if node_type == \"issue\":\n",
    "                node_colors.append(\"lightgray\")\n",
    "            elif node_type == \"hypothesis\":\n",
    "                status = data.get(\"status\", \"active\")\n",
    "                if status == \"closed\":\n",
    "                    node_colors.append(\"lightcoral\")\n",
    "                elif status == \"rejected\":\n",
    "                    node_colors.append(\"gainsboro\")\n",
    "                elif status == \"narrowed\":\n",
    "                    node_colors.append(\"khaki\")\n",
    "                else:\n",
    "                    node_colors.append(\"lightskyblue\")\n",
    "            elif node_type == \"factor\":\n",
    "                node_colors.append(\"lightgreen\")\n",
    "            elif node_type == \"evidence\":\n",
    "                node_colors.append(\"plum\")\n",
    "            else:\n",
    "                node_colors.append(\"white\")\n",
    "\n",
    "        plt.figure(figsize=(14, 9))\n",
    "        nx.draw_networkx_nodes(G, pos, node_color=node_colors, node_size=2400, edgecolors=\"black\")\n",
    "        nx.draw_networkx_edges(G, pos, arrows=True, arrowstyle=\"->\", arrowsize=16, width=1.5)\n",
    "        nx.draw_networkx_labels(G, pos, font_size=8)\n",
    "\n",
    "        plt.title(\"RCA Reasoning Scaffold\", fontsize=14)\n",
    "        plt.axis(\"off\")\n",
    "        plt.tight_layout()\n",
    "        plt.savefig(save_path, dpi=200)\n",
    "        plt.close()\n",
    "\n",
    "\n",
    "# =========================\n",
    "# Example run\n",
    "# =========================\n",
    "\n",
    "def build_example_case() -> RCAReasoningScaffolder:\n",
    "    tool = RCAReasoningScaffolder(\n",
    "        issue=\"Deviation in GMP environmental monitoring record review\"\n",
    "    )\n",
    "\n",
    "    h1 = tool.add_hypothesis(\"Sampling procedure was not followed correctly\")\n",
    "    h2 = tool.add_hypothesis(\"Environmental fluctuation affected the result\")\n",
    "    h3 = tool.add_hypothesis(\"Documentation entry compressed multiple contributing factors\")\n",
    "\n",
    "    tool.add_factor(h1, \"Analyst may have misunderstood the sequence of sampling steps\")\n",
    "    tool.add_factor(h1, \"Procedure required repeated cross-checking across sections\")\n",
    "    tool.add_evidence(h1, \"Step order confusion was mentioned during retrospective questioning\")\n",
    "    tool.add_note(h1, \"Possible procedural ambiguity rather than simple operator negligence\")\n",
    "\n",
    "    tool.add_factor(h2, \"Temporary room condition shift may have influenced results\")\n",
    "    tool.add_factor(h2, \"Monitoring context was not stable across the whole observation period\")\n",
    "    tool.add_evidence(h2, \"Environmental log showed minor fluctuation near deviation time\")\n",
    "    tool.add_note(h2, \"Needs comparison with adjacent monitoring intervals\")\n",
    "\n",
    "    tool.add_factor(h3, \"Final RCA format pushed reasoning toward a single neat explanation\")\n",
    "    tool.add_factor(h3, \"Alternative causal paths became less visible during write-up\")\n",
    "    tool.add_evidence(h3, \"Draft notes contained broader possibilities than final narrative\")\n",
    "    tool.add_note(h3, \"Supports the idea of narrative compression under documentation pressure\")\n",
    "\n",
    "    tool.update_status(h2, \"narrowed\")\n",
    "\n",
    "    return tool\n",
    "\n",
    "\n",
    "def main():\n",
    "    tool = build_example_case()\n",
    "\n",
    "    # Console summary\n",
    "    tool.print_summary()\n",
    "\n",
    "    # DataFrame summary\n",
    "    df = tool.summary_table()\n",
    "    print(\"SUMMARY TABLE\")\n",
    "    print(df.to_string(index=False))\n",
    "\n",
    "    # Save CSV for later use in Streamlit\n",
    "    csv_path = \"rca_summary_table.csv\"\n",
    "    df.to_csv(csv_path, index=False)\n",
    "    print(f\"\\nSaved summary table to: {csv_path}\")\n",
    "\n",
    "    # Save graph\n",
    "    graph_path = \"rca_reasoning_graph.png\"\n",
    "    tool.plot_graph(save_path=graph_path)\n",
    "    print(f\"Saved graph to: {graph_path}\")\n",
    "\n",
    "    # Example warning check\n",
    "    check = tool.check_premature_closure()\n",
    "    print(\"\\nPREMATURE CLOSURE CHECK\")\n",
    "    print(check)\n",
    "\n",
    "    # Optional: simulate overly narrow reasoning\n",
    "    print(\"\\nSIMULATING NARROWING...\")\n",
    "    tool.update_status(\"H2\", \"rejected\")\n",
    "    tool.update_status(\"H3\", \"rejected\")\n",
    "    narrowed_check = tool.check_premature_closure()\n",
    "    print(narrowed_check)\n",
    "\n",
    "    # Optional: close one hypothesis\n",
    "    tool.set_final_closure(\"H1\")\n",
    "    print(f\"\\nFinal closure set to: {tool.rca.final_closure}\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "032eda74-3b00-4404-a365-1adfc1762785",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
